module Scenic
  module Dependencies
    class Dependency
      attr_reader from: String
      attr_reader to: String

      def initialize: (from: String, to: String) -> void

      def self.from_hash_list: (Array[{ 'from' => String, 'to' => String }]) -> Array[Dependency]
    end
  end
end
