module Scenic
  module Dependencies
    interface _DependencyLike
      def from: -> Scenic::Dependencies::View
      def to: -> Scenic::Dependencies::View
    end

    class Dependency
      attr_reader from: Scenic::Dependencies::View
      attr_reader to: Scenic::Dependencies::View

      def initialize: (from: Scenic::Dependencies::View, to: Scenic::Dependencies::View) -> void

      def ==: (_DependencyLike) -> bool

      def to_s: -> String
      def inspect: -> String

      def self.from_hash: ({ 'from' => String, 'from_materialized' => bool, 'to' => String, 'to_materialized' => bool }) -> Dependency
    end
  end
end
