module Scenic
  module Dependencies
    class Dependency
      attr_reader from: String
      attr_reader to: String

      def initialize: (from: String, to: String) -> void

      def to_s: -> String
      def inspect: -> String

      def self.from_hash: ({ 'from' => String, 'to' => String }) -> Dependency
    end
  end
end
