require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Layout/LineLength:
  Max: 120

RSpec/FilePath:
  Exclude:
    - spec/generators/**/*.rb

RSpec/MultipleMemoizedHelpers:
  Max: 6
