module Scenic
  module Cascade
    module DefinitionFinder
      module ClassMethods
        def find_definitions_of: (String) -> Array[Scenic::Definition]
        def find_latest_definition_of: (String) -> Scenic::Definition

        private

        def go: (String, Integer) -> Array[Scenic::Definition]
      end
    end
  end
end
