module Scenic
  module Cascade
    module DependentFinder
      module ClassMethods
        DEPENDANT_SQL: String

        def view_dependents_of: (String, ?recursive: bool) -> Array[Scenic::Cascade::Dependency]
        alias view_dependants_of view_dependents_of
      end
    end
  end
end
