module Scenic
  module Generators
    module View
      class CascadeGenerator < Scenic::Generators::ViewGenerator
        def create_migration_file: -> void

        private

        def dependents: -> Array[Scenic::Cascade::ViewWithVersion]
      end
    end
  end
end
