module Scenic
  module Generators
    class ViewGenerator
      def self.source_root: (String?) -> void
      def plural_name: -> String
      def plural_file_name: -> String
      def migration_template: (String, String) -> void

      def creating_new_view?: -> bool
      def destroying_initial_view?: -> bool
      def version: -> String
    end
  end
end
