name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.2'

    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run bin/setup
      run: bin/setup
    - name: Run the default task
      run: bundle exec rake
      env:
        POSTGRES_HOST: localhost
        POSTGRES_DB: testdb
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
