name: Publish gem
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - run: gem build
      - run: gem publish
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
